// Sample plant data for Foliage Farm
const plantsData = [
  // Andhra Pradesh Plants
  {
    id: 1,
    name: "Red Sanders",
    scientificName: "Pterocarpus santalinus",
    category: "tree",
    state: "andhra-pradesh",
    environment: "outdoor",
    weather: "tropical",
    soil: "loamy",
    terrain: "hills",
    usage: ["medicinal", "ornamental"],
    rating: 4.8,
    price: 1200,
    originalPrice: 1500,
    discount: 20,
    image: "https://source.unsplash.com/random/300x300/?tree,red",
    description: "Red Sanders is a rare and endemic tree species found in the forests of Andhra Pradesh. It's highly valued for its rich red wood and medicinal properties.",
    details: {
      height: "Up to 10 meters",
      waterNeeds: "Moderate",
      sunlight: "Full sun",
      growthRate: "Slow",
      lifespan: "Over 100 years",
      difficulty: "Moderate"
    },
    isNew: false,
    isSale: true,
    inStock: true
  },
  {
    id: 2,
    name: "Neem Tree",
    scientificName: "Azadirachta indica",
    category: "tree",
    state: "andhra-pradesh",
    environment: "outdoor",
    weather: "tropical",
    soil: "sandy",
    terrain: "plains",
    usage: ["medicinal", "religious"],
    rating: 4.9,
    price: 800,
    originalPrice: 800,
    discount: 0,
    image: "https://source.unsplash.com/random/300x300/?neem,tree",
    description: "Neem is a fast-growing tree native to the Indian subcontinent. It's known for its medicinal properties and is considered sacred in many parts of India.",
    details: {
      height: "15-20 meters",
      waterNeeds: "Low",
      sunlight: "Full sun",
      growthRate: "Fast",
      lifespan: "150-200 years",
      difficulty: "Easy"
    },
    isNew: false,
    isSale: false,
    inStock: true
  },
  {
    id: 3,
    name: "Peepal Tree",
    scientificName: "Ficus religiosa",
    category: "tree",
    state: "andhra-pradesh",
    environment: "outdoor",
    weather: "tropical",
    soil: "loamy",
    terrain: "plains",
    usage: ["religious", "medicinal"],
    rating: 4.7,
    price: 950,
    originalPrice: 1100,
    discount: 14,
    image: "https://source.unsplash.com/random/300x300/?peepal,tree",
    description: "The Peepal tree is considered sacred in Hinduism, Buddhism, and Jainism. It has heart-shaped leaves and is known for its medicinal properties.",
    details: {
      height: "Up to 30 meters",
      waterNeeds: "Moderate",
      sunlight: "Full sun",
      growthRate: "Fast",
      lifespan: "Over 100 years",
      difficulty: "Easy"
    },
    isNew: false,
    isSale: true,
    inStock: true
  },
  {
    id: 4,
    name: "Tulsi Plant",
    scientificName: "Ocimum tenuiflorum",
    category: "herb",
    state: "andhra-pradesh",
    environment: "both",
    weather: "tropical",
    soil: "loamy",
    terrain: "plains",
    usage: ["medicinal", "religious", "aromatic"],
    rating: 5.0,
    price: 250,
    originalPrice: 300,
    discount: 17,
    image: "https://source.unsplash.com/random/300x300/?tulsi,basil",
    description: "Tulsi or Holy Basil is a sacred plant in Hindu tradition. It's known for its medicinal properties and is commonly grown in homes and temples.",
    details: {
      height: "0.5-1 meter",
      waterNeeds: "Moderate",
      sunlight: "Partial to full sun",
      growthRate: "Fast",
      lifespan: "2-3 years",
      difficulty: "Easy"
    },
    isNew: false,
    isSale: true,
    inStock: true
  },
  {
    id: 5,
    name: "Indian Sandalwood",
    scientificName: "Santalum album",
    category: "tree",
    state: "andhra-pradesh",
    environment: "outdoor",
    weather: "tropical",
    soil: "sandy",
    terrain: "hills",
    usage: ["aromatic", "medicinal", "religious"],
    rating: 4.6,
    price: 1500,
    originalPrice: 1800,
    discount: 17,
    image: "https://source.unsplash.com/random/300x300/?sandalwood,tree",
    description: "Indian Sandalwood is a small tropical tree known for its fragrant heartwood. It's used in perfumes, cosmetics, and religious ceremonies.",
    details: {
      height: "Up to 9 meters",
      waterNeeds: "Low to moderate",
      sunlight: "Full sun",
      growthRate: "Slow",
      lifespan: "40-80 years",
      difficulty: "Difficult"
    },
    isNew: false,
    isSale: true,
    inStock: true
  },

  // Kerala Plants
  {
    id: 6,
    name: "Coconut Palm",
    scientificName: "Cocos nucifera",
    category: "tree",
    state: "kerala",
    environment: "outdoor",
    weather: "tropical",
    soil: "sandy",
    terrain: "coastal",
    usage: ["edible", "ornamental"],
    rating: 4.9,
    price: 1100,
    originalPrice: 1300,
    discount: 15,
    image: "https://source.unsplash.com/random/300x300/?coconut,palm",
    description: "The Coconut Palm is an iconic tree of Kerala, known as the 'Tree of Life'. Every part of the tree is useful, from its fruit to its leaves and trunk.",
    details: {
      height: "20-30 meters",
      waterNeeds: "Moderate",
      sunlight: "Full sun",
      growthRate: "Moderate",
      lifespan: "60-80 years",
      difficulty: "Easy"
    },
    isNew: false,
    isSale: true,
    inStock: true
  },
  {
    id: 7,
    name: "Cardamom",
    scientificName: "Elettaria cardamomum",
    category: "herb",
    state: "kerala",
    environment: "outdoor",
    weather: "tropical",
    soil: "loamy",
    terrain: "hills",
    usage: ["aromatic", "edible", "medicinal"],
    rating: 4.8,
    price: 350,
    originalPrice: 400,
    discount: 13,
    image: "https://source.unsplash.com/random/300x300/?cardamom,spice",
    description: "Cardamom is known as the 'Queen of Spices' and is one of the most expensive spices. It's widely grown in the hills of Kerala and has a unique aroma.",
    details: {
      height: "2-4 meters",
      waterNeeds: "High",
      sunlight: "Partial shade",
      growthRate: "Moderate",
      lifespan: "10-15 years",
      difficulty: "Moderate"
    },
    isNew: true,
    isSale: false,
    inStock: true
  },
  {
    id: 8,
    name: "Black Pepper",
    scientificName: "Piper nigrum",
    category: "climber",
    state: "kerala",
    environment: "outdoor",
    weather: "tropical",
    soil: "loamy",
    terrain: "hills",
    usage: ["edible", "medicinal"],
    rating: 4.7,
    price: 300,
    originalPrice: 350,
    discount: 14,
    image: "https://source.unsplash.com/random/300x300/?pepper,vine",
    description: "Black Pepper, known as 'Black Gold', is a flowering vine cultivated for its fruit, which is dried and used as a spice. Kerala is a major producer of black pepper.",
    details: {
      height: "Up to 10 meters (climbing)",
      waterNeeds: "Moderate to high",
      sunlight: "Partial shade",
      growthRate: "Moderate",
      lifespan: "20-30 years",
      difficulty: "Moderate"
    },
    isNew: false,
    isSale: true,
    inStock: true
  },
  {
    id: 9,
    name: "Indian Rosewood",
    scientificName: "Dalbergia latifolia",
    category: "tree",
    state: "kerala",
    environment: "outdoor",
    weather: "tropical",
    soil: "loamy",
    terrain: "hills",
    usage: ["ornamental"],
    rating: 4.5,
    price: 1300,
    originalPrice: 1500,
    discount: 13,
    image: "https://source.unsplash.com/random/300x300/?rosewood,tree",
    description: "Indian Rosewood is a deciduous tree known for its rich, dark wood. It's highly valued for furniture making and is native to the Western Ghats of Kerala.",
    details: {
      height: "Up to 25 meters",
      waterNeeds: "Moderate",
      sunlight: "Full sun",
      growthRate: "Slow",
      lifespan: "Over 100 years",
      difficulty: "Moderate"
    },
    isNew: false,
    isSale: true,
    inStock: true
  },
  {
    id: 10,
    name: "Jackfruit Tree",
    scientificName: "Artocarpus heterophyllus",
    category: "tree",
    state: "kerala",
    environment: "outdoor",
    weather: "tropical",
    soil: "loamy",
    terrain: "plains",
    usage: ["edible", "medicinal"],
    rating: 4.6,
    price: 900,
    originalPrice: 1000,
    discount: 10,
    image: "https://source.unsplash.com/random/300x300/?jackfruit,tree",
    description: "The Jackfruit tree produces the largest tree-borne fruit in the world. It's the state fruit of Kerala and is known for its versatility in cooking.",
    details: {
      height: "8-25 meters",
      waterNeeds: "Moderate",
      sunlight: "Full sun",
      growthRate: "Fast",
      lifespan: "60-70 years",
      difficulty: "Easy"
    },
    isNew: false,
    isSale: true,
    inStock: true
  },

  // Tamil Nadu Plants
  {
    id: 11,
    name: "Palmyra Palm",
    scientificName: "Borassus flabellifer",
    category: "tree",
    state: "tamil-nadu",
    environment: "outdoor",
    weather: "tropical",
    soil: "sandy",
    terrain: "plains",
    usage: ["edible", "ornamental"],
    rating: 4.7,
    price: 950,
    originalPrice: 1100,
    discount: 14,
    image: "https://source.unsplash.com/random/300x300/?palm,tree",
    description: "The Palmyra Palm is the state tree of Tamil Nadu. It's a versatile tree with every part being useful, from its fruits to its leaves which are used for making handicrafts.",
    details: {
      height: "15-30 meters",
      waterNeeds: "Low",
      sunlight: "Full sun",
      growthRate: "Slow",
      lifespan: "Over 100 years",
      difficulty: "Easy"
    },
    isNew: false,
    isSale: true,
    inStock: true
  },
  {
    id: 12,
    name: "Glory Lily",
    scientificName: "Gloriosa superba",
    category: "climber",
    state: "tamil-nadu",
    environment: "outdoor",
    weather: "tropical",
    soil: "loamy",
    terrain: "plains",
    usage: ["ornamental", "medicinal"],
    rating: 4.8,
    price: 400,
    originalPrice: 450,
    discount: 11,
    image: "https://source.unsplash.com/random/300x300/?lily,flower",
    description: "Glory Lily is the state flower of Tamil Nadu. It's a climbing lily with striking red and yellow flowers and is known for its medicinal properties.",
    details: {
      height: "Up to 5 meters (climbing)",
      waterNeeds: "Moderate",
      sunlight: "Partial to full sun",
      growthRate: "Fast",
      lifespan: "Perennial",
      difficulty: "Moderate"
    },
    isNew: true,
    isSale: false,
    inStock: true
  },
  {
    id: 13,
    name: "Indian Gooseberry",
    scientificName: "Phyllanthus emblica",
    category: "tree",
    state: "tamil-nadu",
    environment: "outdoor",
    weather: "tropical",
    soil: "loamy",
    terrain: "plains",
    usage: ["medicinal", "edible"],
    rating: 4.9,
    price: 700,
    originalPrice: 800,
    discount: 13,
    image: "https://source.unsplash.com/random/300x300/?gooseberry,fruit",
    description: "Indian Gooseberry or Amla is a deciduous tree known for its sour, nutritious fruits. It's highly valued in Ayurvedic medicine and is rich in Vitamin C.",
    details: {
      height: "8-18 meters",
      waterNeeds: "Moderate",
      sunlight: "Full sun",
      growthRate: "Moderate",
      lifespan: "60-70 years",
      difficulty: "Easy"
    },
    isNew: false,
    isSale: true,
    inStock: true
  },
  {
    id: 14,
    name: "Banana Tree",
    scientificName: "Musa paradisiaca",
    category: "herb",
    state: "tamil-nadu",
    environment: "outdoor",
    weather: "tropical",
    soil: "loamy",
    terrain: "plains",
    usage: ["edible", "ornamental"],
    rating: 4.6,
    price: 600,
    originalPrice: 700,
    discount: 14,
    image: "https://source.unsplash.com/random/300x300/?banana,tree",
    description: "The Banana tree is technically a giant herb, not a tree. It's widely cultivated in Tamil Nadu for its nutritious fruits and is considered auspicious in Hindu culture.",
    details: {
      height: "3-9 meters",
      waterNeeds: "High",
      sunlight: "Full sun",
      growthRate: "Fast",
      lifespan: "1-2 years",
      difficulty: "Easy"
    },
    isNew: false,
    isSale: true,
    inStock: true
  },
  {
    id: 15,
    name: "Teak Tree",
    scientificName: "Tectona grandis",
    category: "tree",
    state: "tamil-nadu",
    environment: "outdoor",
    weather: "tropical",
    soil: "loamy",
    terrain: "hills",
    usage: ["ornamental"],
    rating: 4.7,
    price: 1200,
    originalPrice: 1400,
    discount: 14,
    image: "https://source.unsplash.com/random/300x300/?teak,tree",
    description: "Teak is a tropical hardwood tree known for its high-quality timber. It's widely grown in Tamil Nadu and is valued for its durability and water resistance.",
    details: {
      height: "Up to 40 meters",
      waterNeeds: "Moderate",
      sunlight: "Full sun",
      growthRate: "Moderate",
      lifespan: "Over 100 years",
      difficulty: "Moderate"
    },
    isNew: false,
    isSale: true,
    inStock: true
  },

  // West Bengal Plants
  {
    id: 16,
    name: "White Madar",
    scientificName: "Calotropis gigantea",
    category: "shrub",
    state: "west-bengal",
    environment: "outdoor",
    weather: "tropical",
    soil: "sandy",
    terrain: "plains",
    usage: ["medicinal", "religious"],
    rating: 4.5,
    price: 350,
    originalPrice: 400,
    discount: 13,
    image: "https://source.unsplash.com/random/300x300/?white,flower",
    description: "White Madar is a flowering shrub with medicinal properties. It's the state flower of West Bengal and is associated with Lord Shiva in Hindu mythology.",
    details: {
      height: "2-4 meters",
      waterNeeds: "Low",
      sunlight: "Full sun",
      growthRate: "Fast",
      lifespan: "5-10 years",
      difficulty: "Easy"
    },
    isNew: false,
    isSale: true,
    inStock: true
  },
  {
    id: 17,
    name: "Sundari Tree",
    scientificName: "Heritiera fomes",
    category: "tree",
    state: "west-bengal",
    environment: "outdoor",
    weather: "tropical",
    soil: "loamy",
    terrain: "coastal",
    usage: ["ornamental"],
    rating: 4.6,
    price: 900,
    originalPrice: 1000,
    discount: 10,
    image: "https://source.unsplash.com/random/300x300/?mangrove,tree",
    description: "The Sundari tree is a mangrove species that gives the Sundarbans its name. It's adapted to the saline conditions of the delta region and is important for coastal protection.",
    details: {
      height: "15-25 meters",
      waterNeeds: "High",
      sunlight: "Full sun",
      growthRate: "Slow",
      lifespan: "Over 100 years",
      difficulty: "Difficult"
    },
    isNew: false,
    isSale: true,
    inStock: true
  },
  {
    id: 18,
    name: "Night-flowering Jasmine",
    scientificName: "Nyctanthes arbor-tristis",
    category: "shrub",
    state: "west-bengal",
    environment: "outdoor",
    weather: "tropical",
    soil: "loamy",
    terrain: "plains",
    usage: ["ornamental", "aromatic", "medicinal"],
    rating: 4.8,
    price: 450,
    originalPrice: 500,
    discount: 10,
    image: "https://source.unsplash.com/random/300x300/?jasmine,flower",
    description: "Night-flowering Jasmine is a shrub with fragrant white flowers that bloom at night. It's commonly grown in gardens in West Bengal and has medicinal properties.",
    details: {
      height: "2-5 meters",
      waterNeeds: "Moderate",
      sunlight: "Full sun to partial shade",
      growthRate: "Moderate",
      lifespan: "10-15 years",
      difficulty: "Easy"
    },
    isNew: true,
    isSale: false,
    inStock: true
  },
  {
    id: 19,
    name: "Indian Jujube",
    scientificName: "Ziziphus mauritiana",
    category: "tree",
    state: "west-bengal",
    environment: "outdoor",
    weather: "tropical",
    soil: "sandy",
    terrain: "plains",
    usage: ["edible", "medicinal"],
    rating: 4.7,
    price: 650,
    originalPrice: 750,
    discount: 13,
    image: "https://source.unsplash.com/random/300x300/?jujube,fruit",
    description: "Indian Jujube or Ber is a tropical fruit tree widely grown in West Bengal. Its fruits are rich in vitamins and have a sweet-sour taste.",
    details: {
      height: "5-12 meters",
      waterNeeds: "Low",
      sunlight: "Full sun",
      growthRate: "Moderate",
      lifespan: "50-60 years",
      difficulty: "Easy"
    },
    isNew: false,
    isSale: true,
    inStock: true
  },
  {
    id: 20,
    name: "Red Silk Cotton Tree",
    scientificName: "Bombax ceiba",
    category: "tree",
    state: "west-bengal",
    environment: "outdoor",
    weather: "tropical",
    soil: "loamy",
    terrain: "plains",
    usage: ["ornamental", "medicinal"],
    rating: 4.6,
    price: 850,
    originalPrice: 950,
    discount: 11,
    image: "https://source.unsplash.com/random/300x300/?red,flower",
    description: "The Red Silk Cotton Tree is known for its striking red flowers that bloom when the tree is leafless. It's a common sight in West Bengal during spring.",
    details: {
      height: "20-40 meters",
      waterNeeds: "Moderate",
      sunlight: "Full sun",
      growthRate: "Fast",
      lifespan: "60-70 years",
      difficulty: "Moderate"
    },
    isNew: false,
    isSale: true,
    inStock: true
  },

  // Maharashtra Plants
  {
    id: 21,
    name: "Jarul",
    scientificName: "Lagerstroemia speciosa",
    category: "tree",
    state: "maharashtra",
    environment: "outdoor",
    weather: "tropical",
    soil: "loamy",
    terrain: "plains",
    usage: ["ornamental", "medicinal"],
    rating: 4.7,
    price: 750,
    originalPrice: 850,
    discount: 12,
    image: "https://source.unsplash.com/random/300x300/?purple,flower",
    description: "Jarul is the state flower of Maharashtra. It's a deciduous tree with beautiful purple-pink flowers and is known for its medicinal properties.",
    details: {
      height: "15-25 meters",
      waterNeeds: "Moderate",
      sunlight: "Full sun",
      growthRate: "Moderate",
      lifespan: "50-60 years",
      difficulty: "Easy"
    },
    isNew: false,
    isSale: true,
    inStock: true
  },
  {
    id: 22,
    name: "Mango Tree",
    scientificName: "Mangifera indica",
    category: "tree",
    state: "maharashtra",
    environment: "outdoor",
    weather: "tropical",
    soil: "loamy",
    terrain: "plains",
    usage: ["edible", "ornamental"],
    rating: 4.9,
    price: 1100,
    originalPrice: 1300,
    discount: 15,
    image: "https://source.unsplash.com/random/300x300/?mango,tree",
    description: "The Mango tree is widely cultivated in Maharashtra for its delicious fruits. Alphonso mangoes from Maharashtra are famous worldwide for their taste and aroma.",
    details: {
      height: "10-40 meters",
      waterNeeds: "Moderate",
      sunlight: "Full sun",
      growthRate: "Moderate",
      lifespan: "Over 100 years",
      difficulty: "Easy"
    },
    isNew: false,
    isSale: true,
    inStock: true
  },
  {
    id: 23,
    name: "Indian Almond",
    scientificName: "Terminalia catappa",
    category: "tree",
    state: "maharashtra",
    environment: "outdoor",
    weather: "tropical",
    soil: "sandy",
    terrain: "coastal",
    usage: ["edible", "ornamental", "medicinal"],
    rating: 4.6,
    price: 800,
    originalPrice: 900,
    discount: 11,
    image: "https://source.unsplash.com/random/300x300/?almond,tree",
    description: "Indian Almond is a large tropical tree common along the coastal areas of Maharashtra. It produces edible nuts and its leaves turn red before falling, adding ornamental value.",
    details: {
      height: "15-25 meters",
      waterNeeds: "Moderate",
      sunlight: "Full sun",
      growthRate: "Fast",
      lifespan: "50-60 years",
      difficulty: "Easy"
    },
    isNew: false,
    isSale: true,
    inStock: true
  },
  {
    id: 24,
    name: "Flame of the Forest",
    scientificName: "Butea monosperma",
    category: "tree",
    state: "maharashtra",
    environment: "outdoor",
    weather: "tropical",
    soil: "loamy",
    terrain: "plains",
    usage: ["ornamental", "medicinal", "religious"],
    rating: 4.8,
    price: 700,
    originalPrice: 800,
    discount: 13,
    image: "https://source.unsplash.com/random/300x300/?orange,flower",
    description: "Flame of the Forest is a deciduous tree known for its bright orange-red flowers. It's a common sight in Maharashtra during spring and has religious significance.",
    details: {
      height: "8-15 meters",
      waterNeeds: "Low",
      sunlight: "Full sun",
      growthRate: "Moderate",
      lifespan: "40-50 years",
      difficulty: "Easy"
    },
    isNew: true,
    isSale: false,
    inStock: true
  },
  {
    id: 25,
    name: "Indian Coral Tree",
    scientificName: "Erythrina variegata",
    category: "tree",
    state: "maharashtra",
    environment: "outdoor",
    weather: "tropical",
    soil: "loamy",
    terrain: "coastal",
    usage: ["ornamental", "medicinal"],
    rating: 4.5,
    price: 650,
    originalPrice: 750,
    discount: 13,
    image: "https://source.unsplash.com/random/300x300/?coral,flower",
    description: "The Indian Coral Tree is known for its vibrant red flowers and thorny trunk. It's commonly found in the coastal regions of Maharashtra and has medicinal properties.",
    details: {
      height: "15-20 meters",
      waterNeeds: "Moderate",
      sunlight: "Full sun",
      growthRate: "Fast",
      lifespan: "30-40 years",
      difficulty: "Moderate"
    },
    isNew: false,
    isSale: true,
    inStock: true
  }
];